# Desafio Técnico – Cientista de Dados

**Cenário**

Evasão de clientes em uma instituição financeira (Exited).

**Objetivo**

Você recebeu um conjunto de dados contendo informações sobre 10.000 clientes de um banco. O conjunto inclui atributos relacionados ao perfil, comportamento e situação financeira de cada cliente. A variável de interesse indica se o cliente permaneceu ou deixou a instituição.

**Tarefa**

Neste desafio, espera-se que você:

    Elabore uma linha de trabalho coerente e bem estruturada, com base no problema apresentado;

    Execute essa linha de ação até o ponto que julgar apropriado, de acordo com seu próprio
    planejamento;

    Utilize esse processo para explorar o comportamento dos dados e levantar hipóteses iniciais
    sobre os fatores mais relevantes relacionados à variável de interesse (selecionar as
    variáveis mais importantes para prever o comportamento observado);

    Documente, no próprio código, o planejamento adotado e um resumo das conclusões preliminares
    que surgirem ao longo da execução.

# Sobre os dados

A base disponibilizada é composta por dados estruturados, abrangendo variáveis demográficas, financeiras e operacionais. Trata-se de um conjunto apropriado para abordagens voltadas à compreensão de padrões, levantamento de indicadores e identificação de perfis.

**Dataset fornecido: Churn_Modelling.csv, com as seguintes variáveis:**

| Variável          | Tipo           | Descrição                                          |
| ----------------- | -------------- | -------------------------------------------------- |
| `RowNumber`       | Identificador  | Índice da linha no dataset.                        |
| `CustomerId`      | Identificador  | ID único do cliente.                               |
| `Surname`         | Categórica     | Sobrenome do cliente.                              |
| `CreditScore`     | Numérica       | Pontuação de crédito (quanto maior, melhor).       |
| `Geography`       | Categórica     | País de residência (`France`, `Spain`, `Germany`). |
| `Gender`          | Categórica     | Sexo do cliente (`Male`, `Female`).                |
| `Age`             | Numérica       | Idade do cliente.                                  |
| `Tenure`          | Numérica       | Tempo (em anos) como cliente.                      |
| `Balance`         | Numérica       | Saldo da conta.                                    |
| `NumOfProducts`   | Numérica       | Número de produtos bancários que o cliente possui. |
| `HasCrCard`       | Binária        | Possui cartão de crédito (1 = sim, 0 = não).       |
| `IsActiveMember`  | Binária        | Cliente é ativo (1 = sim, 0 = não).                |
| `EstimatedSalary` | Numérica       | Salário estimado.                                  |
| `Exited`          | Binária (Alvo) | 1 = cliente saiu do banco, 0 = permaneceu.         |

# Acessando o Dataset

In [ ]:
# 📦 ETAPA 1 – Importação de Bibliotecas e Leitura dos Dados

# Bibliotecas essenciais para análise de dados
import numpy as np
import pandas as pd

# (Opcional) Biblioteca para baixar datasets do Kaggle programaticamente
import kagglehub  # Certifique-se de que esta biblioteca está instalada no ambiente

# 🔽 Download do dataset hospedado no Kaggle
# Isso fará o download do dataset para o diretório local do ambiente
path = kagglehub.dataset_download("kartiksaini18/churn-bank-customer")

# Mostra o caminho em que os arquivos foram salvos
print("Caminho para os arquivos do dataset:", path)

# 📄 Leitura do arquivo CSV após download
# Substitua o caminho abaixo se necessário, de acordo com onde o arquivo foi salvo no seu ambiente
df = pd.read_csv("/kaggle/input/churn-bank-customer/Churn_Modelling.csv")

# Visualização das 5 primeiras linhas da base de dados
df.head()

Caminho para os arquivos do dataset: /kaggle/input/churn-bank-customer

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Linha de Trabalho:
- Carregamento do Dataset; ok
- Identificação das features e target; ok
- Tradução das features e target; ok
- Classificação (Nominal, Numérica, ...); ok
- Aplicação de medidas estatísticas (Média, Moda, ...); ok
- Codificação de variáveis categórica, se necessário; ok
- Padronização de variáveis quantitativas; ok
- Verificação de dados faltantes; ok

In [ ]:
#Carregamento do dataset:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
#Identificação das features e target
df_features = df[['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',	'Tenure',	'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']]
df_target = df['Exited']

display(df_features)
display(df_target)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
#Tradução das features e target
#Colunas
df = df.rename(columns={'RowNumber': 'Linha', 'CustomerId': 'IdCliente', 'Surname': 'Sobrenome', 'CreditScore': 'PontuacaoCredito', 'Geography': 'PaisResidencia', 'Gender': 'Sexo', 'Age': 'Idade', 'Tenure': 'Mandato', 'Balance': 'Saldo', 'NumOfProducts': 'NumProdutos', 'HasCrCard': 'CartaoCredito', 'IsActiveMember': 'seAtivo', 'EstimatedSalary': 'SalarioEstimado', 'Exited': 'Saída'})
#Dados
df['PaisResidencia'] = df['PaisResidencia'].replace({'France' : 'França','Spain':'Espanha','Germany':'Alemanha'})
df['Sexo'] = df['Sexo'].replace({'Male' : 'Masculino','Female':'Feminino'})

display(df)

,Linha,IdCliente,Sobrenome,PontuacaoCredito,PaisResidencia,Sexo,Idade,Mandato,Saldo,NumProdutos,CartaoCredito,seAtivo,SalarioEstimado,Saída
0,1,15634602,Hargrave,619,França,Feminino,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Espanha,Feminino,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,França,Feminino,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,França,Feminino,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Espanha,Feminino,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,França,Masculino,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,França,Masculino,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,França,Feminino,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Alemanha,Masculino,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,França,Feminino,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
#Separação de features e target
df_features = df[['Linha', 'IdCliente', 'Sobrenome', 'PontuacaoCredito', 'PaisResidencia', 'Sexo', 'Idade', 'Mandato', 'Saldo', 'NumProdutos', 'CartaoCredito', 'seAtivo', 'SalarioEstimado']]
df_target = df['Saída']

#Separação de variáveis qualititativas e quantitativas
df_qualitativas = df_features[['Linha', 'IdCliente', 'Sobrenome', 'PaisResidencia', 'Sexo', 'CartaoCredito', 'seAtivo']]
df_quantitativas = df_features[['PontuacaoCredito', 'Idade', 'Mandato', 'Saldo', 'NumProdutos', 'SalarioEstimado']]

In [ ]:
#Medidas estatísticas (Qualitiativas)
#Média
df_quantitativas.mean()

PontuacaoCredito       652.000
Idade                   37.000
Mandato                  5.000
Saldo                97198.540
NumProdutos              1.000
SalarioEstimado     100193.915
dtype: float64

In [ ]:
#Moda
df_quantitativas.mode()

   PontuacaoCredito  Idade  Mandato  Saldo  NumProdutos  SalarioEstimado
0               850     37        2    0.0            1         24924.92

In [ ]:
#Mediana
df_quantitativas.median()

PontuacaoCredito       652.000
Idade                   37.000
Mandato                  5.000
Saldo                97198.540
NumProdutos              1.000
SalarioEstimado     100193.915
dtype: float64

In [ ]:
#Verificando a ocorrência (frequência) dos valores qualitativos
df_qualitativas['PaisResidencia'].value_counts()

PaisResidencia
França      5014
Alemanha    2509
Espanha     2477
Name: count, dtype: int64

In [ ]:
df_qualitativas['Sexo'].value_counts()

Sexo
Masculino    5457
Feminino     4543
Name: count, dtype: int64

In [ ]:
df_qualitativas['CartaoCredito'].value_counts()

CartaoCredito
1    7055
0    2945
Name: count, dtype: int64

In [ ]:
df_qualitativas['seAtivo'].value_counts()

seAtivo
1    5151
0    4849
Name: count, dtype: int64

In [ ]:
df_qualitativas['Sobrenome'].value_counts()

Sobrenome
Smith        32
Scott        29
Martin       29
Walker       28
Brown        26
             ..
Hull          1
Sturdee       1
Flannagan     1
Dwyer         1
Corby         1
Name: count, Length: 2932, dtype: int64

In [ ]:
df_qualitativas['IdCliente'].value_counts()

IdCliente
15656710    1
15768163    1
15672754    1
15719276    1
15692664    1
           ..
15737888    1
15701354    1
15619304    1
15647311    1
15634602    1
Name: count, Length: 10000, dtype: int64

In [ ]:
df_qualitativas['Linha'].value_counts()

Linha
9984    1
9983    1
9982    1
9981    1
9980    1
       ..
5       1
4       1
3       1
2       1
1       1
Name: count, Length: 10000, dtype: int64

Analisando as variáveis qualitativas, podemos afirmar que as variáveis "Linha", "IdCliente" e "Sobrenome" não são relevantes para analise pois tem grande variabilidade e existem apenas para identificar as linhas. Dessa forma, serão removidas.

In [ ]:
#Nova tabela após análise
df = df.drop(['Linha', 'IdCliente', 'Sobrenome'], axis=1)

In [ ]:
#Verificação de dados faltantes;
df.isnull().sum()

PontuacaoCredito    0
PaisResidencia      0
Sexo                0
Idade               0
Mandato             0
Saldo               0
NumProdutos         0
CartaoCredito       0
seAtivo             0
SalarioEstimado     0
Saída               0
dtype: int64

In [ ]:
#Separação de variáveis qualititativas e quantitativas
df_qualitativas = df[['PaisResidencia', 'Sexo', 'CartaoCredito', 'seAtivo']]
df_quantitativas = df[['PontuacaoCredito', 'Idade', 'Mandato', 'Saldo', 'NumProdutos', 'SalarioEstimado']]

In [ ]:
#Codificação de variáveis categórica
df_qualitativas['PaisResidencia'] = pd.factorize(df['PaisResidencia'])[0]
df_qualitativas

      PaisResidencia  Sexo  CartaoCredito  seAtivo
0                  0     0              1        1
1                  1     0              0        1
2                  0     0              1        0
3                  0     0              0        0
4                  1     0              1        1
...              ...   ...            ...      ...
9995               0     1              1        0
9996               0     1              1        1
9997               0     0              0        1
9998               2     1              1        0
9999               0     0              1        0

[10000 rows x 4 columns]

In [ ]:
#Normalizando variáveis quantitativas
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_quantitativas = pd.DataFrame(scaler.fit_transform(df_quantitativas), columns=df_quantitativas.columns)
df_quantitativas

,PontuacaoCredito,Idade,Mandato,Saldo,NumProdutos,SalarioEstimado
0,0.538,0.324324,0.2,0.000000,0.000000,0.506735
1,0.516,0.310811,0.1,0.334031,0.000000,0.562709
2,0.304,0.324324,0.8,0.636357,0.666667,0.569654
3,0.698,0.283784,0.1,0.000000,0.333333,0.469120
4,1.000,0.337838,0.2,0.500246,0.000000,0.395400
...,...,...,...,...,...,...
9995,0.842,0.283784,0.5,0.000000,0.333333,0.481341
9996,0.332,0.229730,1.0,0.228657,0.000000,0.508490
9997,0.718,0.243243,0.7,0.000000,0.000000,0.210390
9998,0.844,0.324324,0.3,0.299226,0.333333,0.464429
9999,0.884,0.135135,0.4,0.518708,0.000000,0.190914

In [ ]:
#Unindo variáveis qualitaivas e quantitivas finais com o target
df = pd.concat([df_qualitativas, df_quantitativas, df_target], axis=1)
df

,PaisResidencia,Sexo,CartaoCredito,seAtivo,PontuacaoCredito,Idade,Mandato,Saldo,NumProdutos,SalarioEstimado,Saída
0,0,0,1,1,0.538,0.324324,0.2,0.000000,0.000000,0.506735,1
1,1,0,0,1,0.516,0.310811,0.1,0.334031,0.000000,0.562709,0
2,0,0,1,0,0.304,0.324324,0.8,0.636357,0.666667,0.569654,1
3,0,0,0,0,0.698,0.283784,0.1,0.000000,0.333333,0.469120,0
4,1,0,1,1,1.000,0.337838,0.2,0.500246,0.000000,0.395400,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,0,1,1,0,0.842,0.283784,0.5,0.000000,0.333333,0.481341,0
9996,0,1,1,1,0.332,0.229730,1.0,0.228657,0.000000,0.508490,0
9997,0,0,0,1,0.718,0.243243,0.7,0.000000,0.000000,0.210390,1
9998,2,1,1,0,0.844,0.324324,0.3,0.299226,0.333333,0.464429,1
9999,0,0,1,0,0.884,0.135135,0.4,0.518708,0.000000,0.190914,0

A tabela acima está no modo mais apropriado para se selecionar as melhores features para se trabalhar algum modelo. Porém, ainda assim podemos utilizar métodos como o SelectKBest para se obter as melhores variáveis qualitativas e quantitativas, utilizando o cálculo do Qui-Quadrado e F-Score.

In [ ]:
#Utilizando SelectKBest
from sklearn.feature_selection import SelectKBest, chi2, f_classif

#Aplicação do SelectKBest para variáveis:
#Categóricas (Qui-Quadrado)
best_cat = SelectKBest(chi2, k="all")
best_cat.fit(df_, target)
cat_scores = best_cat.scores_
#Numéricas (R2)
best_num = SelectKBest(r2_score, k="all")
num_scores = list()
for column in num_df.columns:
  best_num.fit(num_df[[column]], target)
  num_scores.append(best_num.scores_)

#Criação do dataframe de resultados
cat_df = pd.DataFrame(cat_scores, index=cat_df.columns, columns=['Chi-Quadrado'])
num_df = pd.DataFrame(num_scores, index=num_df.columns, columns=['R2'])
#Ordenando do maior para o menor
cat_df = cat_df.sort_values(by='Chi-Quadrado', ascending=False)
num_df = num_df.sort_values(by='R2', ascending=False)
#Printando resultados
display(cat_df, num_df)